version: '3.9'
services:
  db:
    image: postgres
    env_file:
      - .env

  nest-api:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    expose:
      - "3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
